### ISSUE TITLE
Remove batch modification and reading of multiple indexes in variables (and consort)

### ISSUE THREAD

**Issue by xhtmlboi** [pytre/mre#1]
I think it would be better to implant loops "à La Pico" in the Event-Making rather than implementing shortcuts based on hacks.

- It makes code complex to read;
- it is impossible to document properly;
- it makes the type of accessors complicated (`single value | array`).

Using Loops, you can deal with what you want!

**Comment by pytre** [comment]
Yes, you're definitively right!
Thanks (glad to see you, coming in back in the RPGMAKER game)
